[versions]
neoforge = "26.1.0.0-alpha.0+snapshot-6.20260210.064003"
mdg = "2.0.140"
neoforgeRange = { require = "[26.1.0.0-alpha,)", prefer = "26.1.0.0-alpha.0+snapshot-6.20260210.064003" }
neoform = "no"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
