[versions]
neoforge = "26.1.0.17-beta"
mdg = "2.0.141"
neoforgeRange = { require = "[26.1.0.1-beta,)", prefer = "26.1.0.17-beta" }
neoform = "no"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
