[versions]
neoforge = "26.2.0.7-beta"
mdg = "2.0.141"
neoforgeRange = { require = "[26.2.0.7-beta,)", prefer = "26.2.0.7-beta" }
neoform = "no"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
